events {}

http {
    upstream rrhh_frontend {
        server frontend:4173;
    }

    upstream rrhh_backend {
        server backend:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://rrhh_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://rrhh_frontend;
            proxy_set_header Host $host;
        }
    }
}